### ISSUE TITLE
Empty groups

### ISSUE THREAD

**Issue by eloo** [pkcakeout/pushgateway#3]
Hey there,

i just realized that with your current version the pushgateway holds empty groups in its web-ui.
Maybe you could check how we can automatically remove them?
Thanks for your work

**Comment by MrApplejuice** [comment]
With the recent addition of exlicit push-date metrics, this is not suer straight-forward anymore. Groups will not remain enpty since the push-dates remain valid forever. So this is sort-of fixed. However, the real question is, I think: should groups have a lifetime?

This makes this a bigger new feature: assigning lifetimes to groups. I am not sure how this should be implemented, if at all. I will put the down in the priority list for a bit...

**Comment by eloo** [comment]
ah okay.. will check this with the new version a few days

**Comment by eloo** [comment]
okay, so we are now facing stale groups with exactly one metric.. the push_time_seconds.
are there any plans to clean such groups up?
